import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Search, BadgeCheck, MapPin } from 'lucide-react';
import API from '../services/api';

export default function ScoutDirectory() {
  const [scouts, setScouts] = useState([]); const [filters, setFilters] = useState({ search: '', sport: '', region: '', organization_type: '' }); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const timer = setTimeout(async () => { try { setLoading(true); const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value)); const response = await API.get('/api/v1/scouts', { params }); setScouts(response.data); } catch { setError('Unable to load scouts right now.'); } finally { setLoading(false); } }, 250); return () => clearTimeout(timer); }, [filters]);
  const change = (event) => setFilters({ ...filters, [event.target.name]: event.target.value });
  return <main className="mx-auto max-w-6xl px-4 py-8">
    <div className="mb-7"><p className="text-sm font-semibold text-blue-600">Verified professionals</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Find a Scout</h1><p className="mt-2 text-slate-500">Discover approved talent scouts and request an evaluation of your results.</p></div>
    <div className="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-4"><label className="relative sm:col-span-2"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input name="search" value={filters.search} onChange={change} className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-sm" placeholder="Search name, organisation, or specialisation" /></label><input name="sport" value={filters.sport} onChange={change} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Sport" /><input name="region" value={filters.region} onChange={change} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Region" /><select name="organization_type" value={filters.organization_type} onChange={change} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">All organisation types</option><option>Club</option><option>National</option><option>Independent</option><option>Academy</option></select></div>
    {error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    {loading ? <p className="text-sm text-slate-500">Loading verified scouts…</p> : scouts.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">No verified scouts match those filters yet.</div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{scouts.map((scout) => <Link key={scout.id} to={`/scouts/${scout.id}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-blue-100 font-bold text-blue-700">{(scout.user.profile?.full_name || 'S').slice(0, 1)}</div><span className="flex items-center gap-1 text-xs font-semibold text-blue-600"><BadgeCheck size={16}/> Verified</span></div><h2 className="mt-4 font-semibold text-slate-900">{scout.user.profile?.full_name || 'Scout'}</h2><p className="text-sm text-slate-500">{scout.organization} · {scout.organization_type}</p><p className="mt-3 flex items-center gap-1 text-xs text-slate-500"><MapPin size={14}/>{scout.region}</p><div className="mt-4 flex flex-wrap gap-2">{scout.specialization.map((tag) => <span key={tag} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-600">{tag}</span>)}</div></Link>)}</div>}
  </main>;
}
