import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { BadgeCheck, MapPin } from 'lucide-react';
import API from '../services/api';
import { getAssessmentHistory } from '../utils/assessmentStorage';

export default function ScoutProfilePage() {
  const { id } = useParams(); const [scout, setScout] = useState(null); const [message, setMessage] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { API.get(`/api/v1/scouts/${id}`).then((res) => setScout(res.data)).catch(() => setNotice('This scout is not available.')); }, [id]);
  const request = async () => { try { await API.post(`/api/v1/scouts/${id}/evaluation-requests`, { message, assessment_data: getAssessmentHistory() }); setNotice('Your evaluation request has been sent.'); setMessage(''); } catch (err) { setNotice(err.response?.data?.error || 'Could not send your request.'); } };
  if (!scout) return <main className="mx-auto max-w-3xl px-4 py-10 text-slate-500">{notice || 'Loading scout profile…'}</main>;
  return <main className="mx-auto max-w-3xl px-4 py-8"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-blue-100 text-xl font-bold text-blue-700">{(scout.user.profile?.full_name || 'S').slice(0, 1)}</div><div><h1 className="text-2xl font-semibold">{scout.user.profile?.full_name || 'Scout'}</h1><p className="text-slate-500">{scout.organization} · {scout.organization_type}</p><p className="mt-1 flex items-center gap-1 text-sm text-slate-500"><MapPin size={14}/>{scout.region}</p></div></div><p className="mt-6 leading-7 text-slate-600">{scout.bio}</p><div className="mt-5 flex flex-wrap gap-2">{scout.sports.map((tag) => <span key={tag} className="rounded-full bg-blue-50 px-3 py-1 text-sm text-blue-700">{tag}</span>)}{scout.specialization.map((tag) => <span key={tag} className="rounded-full bg-slate-100 px-3 py-1 text-sm text-slate-600">{tag}</span>)}</div><div className="mt-6 rounded-xl bg-slate-50 p-4"><p className="font-medium">What they look for</p><p className="mt-1 text-sm text-slate-600">{scout.metrics_sought || 'Assessment results and athletic potential.'}</p></div>{(scout.contact_email || scout.linkedin_url) && <div className="mt-4 flex gap-3 text-sm font-medium text-blue-600">{scout.contact_email && <a href={`mailto:${scout.contact_email}`}>Email scout</a>}{scout.linkedin_url && <a href={scout.linkedin_url} target="_blank" rel="noreferrer">LinkedIn</a>}</div>}<p className="mt-4 flex items-center gap-1 text-sm font-medium text-blue-600"><BadgeCheck size={17}/> Verified Scout</p></section><section className="mt-5 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Request evaluation</h2><p className="mt-1 text-sm text-slate-500">Share your saved AI assessment results with this scout for review.</p><textarea value={message} onChange={(e) => setMessage(e.target.value)} className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm" rows="3" placeholder="Add a short note (optional)"/><button onClick={request} className="mt-3 rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white">Request evaluation</button>{notice && <p className="mt-3 text-sm text-slate-600">{notice}</p>}</section></main>;
}
