version: '3.8'

services:
  api:
    build: .
    container_name: mediapipeline_api
    ports:
      - "8001:8001"
    volumes:
      - ./storage:/app/storage
    environment:
      - LOG_LEVEL=INFO
    restart: unless-stopped
